version: '3'

services:
  webapp:
    build:
      context: ./webapp-ui/
    container_name: webapp
    ports:
      - "8080:8080"
    restart: always
    environment:
      URL: jdbc:mysql://db:3306/phonebook?useUnicode=yes&characterEncoding=UTF-8
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: mySuperSecretPassword
    restart: always
    ports:
      - "3306:3306"

  # Cache implementation
  redis:
    image: "redis:4.0"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
