apiVersion: 1

datasources:
  - name: metrics
    database: metrics
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: influxdb
    password: influxdb
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials: false
    version: 1
    editable: true